name: 'Close stale issues'
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:
    if: github.repository == 'edgardmessias/glpi-singlesignon'
    permissions:
      issues: write  # for actions/stale to close stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >-
            There has been no activity on this issue for some time and therefore it is considered stale
            and will be closed automatically in 10 days.
            
            
            If this issue is related to a bug, please try to reproduce on latest release. If the problem persist,
            feel free to add a comment to revive this issue.
          days-before-issue-stale: 60
          days-before-pr-stale: -1 # PR will be marked as stale manually.
          days-before-close: 10
          exempt-issue-labels: "bug,enhancement,question,security" # Issues with "bug", "enhancement", "question" or "security" labels will not be marked as stale
          exempt-all-milestones: true # Do not check issues/PR with defined milestone.
          ascending: true # First check older issues/PR.
          operations-per-run: 750 # Max API calls per run.
